### ISSUE TITLE
Pug

### ISSUE THREAD

**Issue by DmitrijMTP** [Ramil192/Task2#10]
1. Зачем пустой цикл ?
![2021-06-23_22-39](https://user-images.githubusercontent.com/85491485/123158007-edbf5900-d473-11eb-83d0-56d9597cf8a4.png)
2. В pug тоже лучше разделять код на смысловые блоки, а не единой портянкой. Также лучше читается? 
![2021-06-23_22-43](https://user-images.githubusercontent.com/85491485/123158509-8c4bba00-d474-11eb-90e9-15bb96a29898.png)

3. include лучше размещать в начале файла

**Comment by Ramil192** [comment]
1 он не  пустой.
![image](https://user-images.githubusercontent.com/61628421/123521680-cb6e4b00-d6c0-11eb-93ef-726fbf3501d2.png)

**Comment by DmitrijMTP** [comment]
![2021-07-02_23-06](https://user-images.githubusercontent.com/85491485/124323607-42f11e00-db8a-11eb-963e-5fd01e391624.png)
Странное именование часть в camelCase, куча сокращений

**Comment by DmitrijMTP** [comment]
Сокращения остались 
![2021-07-06_09-45](https://user-images.githubusercontent.com/85491485/124554786-039f2780-de3f-11eb-9079-5038b80a7686.png)
![2021-07-06_09-46](https://user-images.githubusercontent.com/85491485/124554875-1c0f4200-de3f-11eb-9c38-8b90bbf649a5.png)
![2021-07-06_09-47](https://user-images.githubusercontent.com/85491485/124555010-42cd7880-de3f-11eb-9585-91b1753ba6e4.png)
![2021-07-06_09-48](https://user-images.githubusercontent.com/85491485/124555115-61337400-de3f-11eb-899d-436ef3a4e4d5.png)
