### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by DmitrijMTP** [Ramil192/Task2#11]
![2021-06-29_11-30](https://user-images.githubusercontent.com/85491485/123764780-c500ee80-d8cd-11eb-8781-0fed313f4dc6.png)
Бэм блок полностью независимый, у тебя почему-то импортируются файлы из других блоков, все что нужно для работы блока должно быть внутри него.

**Comment by Ramil192** [comment]
1 Это у меня не блок а страница  ,
2 Это у меня точка входа , и тут только то что нужно для работы именно для этой страницы , а не для всего приложения.

**Comment by DmitrijMTP** [comment]
Хорошо пусть будет страница, почему туда импортируются стили,js из блоков? Тебе нужно подключить сам блок(миксин) в pug, а он уже сам должен управлять всеми стилями и js.

**Comment by Ramil192** [comment]
Это точка входа , если не импортировать в точку входа ,стили не подключатся и js не применяться

**Comment by DmitrijMTP** [comment]
> Это точка входа , если не импортировать в точку входа ,стили не подключатся и js не применяться

Тебе нужно будет настроить автоматические импорты через webpack, а точка входа будет одна какой-нибудь app.js или index.js

**Comment by DmitrijMTP** [comment]
1.Блок calendar, почему тут файл  datepicker.scss?
2.
![2021-07-02_23-42](https://user-images.githubusercontent.com/85491485/124326533-39b68000-db8f-11eb-9ff6-62b59a10dbe0.png)
Повтори как именуются модификаторы, тебе в данном случае подойдет "ключ-значение"

**Comment by Ramil192** [comment]
1 datepicker.scss там у меня мои scss стили чтобы подогнать календарь под макет  , назвал так потому что  
![image](https://user-images.githubusercontent.com/61628421/124360611-63c17e00-dc33-11eb-8a62-90162caa6f3e.png)
 у самой библиотеки такое название есть.

**Comment by DmitrijMTP** [comment]
> 1 datepicker.scss там у меня мои scss стили чтобы подогнать календарь под макет , назвал так потому что
> ![image](https://user-images.githubusercontent.com/61628421/124360611-63c17e00-dc33-11eb-8a62-90162caa6f3e.png)
> у самой библиотеки такое название есть.

 Можно вынести в отдельный блок и просто подключать где нужно, но в данном блоке может быть только calendar.scss файл стилей

**Comment by Ramil192** [comment]
Не уверен что правильно сделал.

**Comment by DmitrijMTP** [comment]
В Like-button: если это модификатор ключ-значение то должно быть и ключ и значение, если булевый то action не подходит, он должен предполагать  "true|false" 
![2021-07-08_10-35](https://user-images.githubusercontent.com/85491485/124881614-3c263900-dfd8-11eb-8587-ca31283eff66.png)
