### ISSUE TITLE
Структура

### ISSUE THREAD

**Issue by DmitrijMTP** [Ramil192/Task2#12]
1.
![2021-06-29_11-38](https://user-images.githubusercontent.com/85491485/123765611-90416700-d8ce-11eb-921d-7d5483d80bc5.png)
Card, form-elements и т.п. это отдельные страницы? В pages должны быть только странницы index.pug и т.п.,почему-то там находятся стили, js. Если это блоки они должны быть в блоках

2.
![2021-06-29_11-46](https://user-images.githubusercontent.com/85491485/123766839-b287b480-d8cf-11eb-8d24-6b95705a6ee3.png)
Если изображения используется только в одном блоке они должны быть внутри него, в общей директории с изображениями должны быть только файлы, которые используются в множестве мест.

**Comment by Ramil192** [comment]
Вопрос про первый пункт ,
В папке pages только страницы , 
js это точка входа так как я использую чанки. https://webstool.ru/webpack-neskolko-tochek-vxoda-i-neskolko-bibliotek.html 
scss это стили самой страницы, 

Тогда где они должны быть  если не в одной папке ?

**Comment by DmitrijMTP** [comment]
> Вопрос про первый пункт ,
> В папке pages только страницы ,
> js это точка входа так как я использую чанки. https://webstool.ru/webpack-neskolko-tochek-vxoda-i-neskolko-bibliotek.html
> scss это стили самой страницы,
> 
> Тогда где они должны быть если не в одной папке ?

Уточнил, пункт 2 снимается, разрешается

**Comment by DmitrijMTP** [comment]
![2021-07-03_00-11](https://user-images.githubusercontent.com/85491485/124328950-3b824280-db93-11eb-9508-8ea87d9e7306.png)
1.Например, эти файлы используются только в одном месте, тогда они должны быть в своем блоке в папке images, например.
2.Читая их название другой разработчик должен понимать что там находится(хотя бы примерно), а не угадывать

**Comment by DmitrijMTP** [comment]
Небольшой момент остался, все изображения у тебя именуются с маленькой буквы, и пара с большой. Это не так значительно, но лучше сделать единообразно 
![2021-07-06_10-05](https://user-images.githubusercontent.com/85491485/124557403-22eb8400-de42-11eb-968a-20d305e3f442.png)
