### ISSUE TITLE
Scss

### ISSUE THREAD

**Issue by DmitrijMTP** [Ramil192/Task2#13]
1. Не нужно закрывать issues, когда проверю закрою сам, если нужно будет
2. Снова сокращения, еще можно понять img, хотя тоже не желательно, но imgs вообще не понятно. Это же касается и именования папок и файлов
![2021-07-02_22-54](https://user-images.githubusercontent.com/85491485/124322803-cc075580-db88-11eb-8523-a246a74b7b71.png)
3.
![2021-07-02_23-46](https://user-images.githubusercontent.com/85491485/124326770-b21d4100-db8f-11eb-9051-0a4b6ffaea97.png)
Отрицательные марджины не используются [link](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#2.4)

**Comment by Ramil192** [comment]
Отрицательные марджины  только тут остались , так как это левая библиотека  и тут не как не не обойтись без их.
 Может простительно ?
 ![image](https://user-images.githubusercontent.com/61628421/124391047-4f46b980-dcf7-11eb-9d59-0ef786c6ed6f.png)
