### ISSUE TITLE
Form-elements page

### ISSUE THREAD

**Issue by DmitrijMTP** [Ramil192/Task2#15]
Слайдер:
Должно быть в одну линию
![2021-07-06_10-41](https://user-images.githubusercontent.com/85491485/124561740-e53d2a00-de46-11eb-8f2b-64fc1152c491.png)
Не получается сдвинуть ползунки
https://user-images.githubusercontent.com/85491485/124564020-48c85700-de49-11eb-949d-64b1ae692ca1.mp4

like buttons:
Это кнопки, и они интерактивные, с курсором pointer 
Цвет текста у них разный должен быть, иконки с текстом не совсем по центру выравнены
![2021-07-06_11-04](https://user-images.githubusercontent.com/85491485/124564946-3b5f9c80-de4a-11eb-9f9c-d943961d7f29.png)

Dropdown:
"Уголка" вверху нет в макетах
![2021-07-06_11-13](https://user-images.githubusercontent.com/85491485/124566019-54b51880-de4b-11eb-9c1d-f1c7591cef12.png)

В "сколько гостей" кнопка применить не работает, тут тоже нужно показать пользователю, что элемент интерактивный и можно с ним взаимодействовать, сделать курсор pointer.
 С нулевым количеством не нужно отображать:
![2021-07-06_11-33](https://user-images.githubusercontent.com/85491485/124568879-14a36500-de4e-11eb-8059-068452c956f6.png)

Masked input:
Тут должен быть не календарь, а маска
![2021-07-06_11-20](https://user-images.githubusercontent.com/85491485/124567022-41ef1380-de4c-11eb-951a-09a4b4b889f6.png)
Вот похожее на такое, только в соответствии с макетом:
https://user-images.githubusercontent.com/85491485/124567843-056fe780-de4d-11eb-9ba0-0c661c0996ab.mp4

Subscription input:
![2021-07-06_11-27](https://user-images.githubusercontent.com/85491485/124568190-54b61800-de4d-11eb-883b-8a7c4c6f5df3.png)
Существует type="email" у инпута, стрелочка тоже интерактивная

**Comment by DmitrijMTP** [comment]
Слайдер: теперь работает, но подпись также в две строчки

like buttons: тут section по семантике не подходит, больше подойдет button

Dropdown: с нулем отображается 
![2021-07-08_10-50](https://user-images.githubusercontent.com/85491485/124883919-7a245c80-dfda-11eb-92c9-2f4eb264f189.png)

Checkbox: пропали "галки" при checked
![2021-07-08_10-53](https://user-images.githubusercontent.com/85491485/124884398-e606c500-dfda-11eb-8019-b3fd5ac3bf62.png)

**Comment by Ramil192** [comment]
![image](https://user-images.githubusercontent.com/61628421/125085878-b8ea0d80-e0d3-11eb-8a7d-d9cab65bb020.png)
у меня вот так , у меня гугол

**Comment by DmitrijMTP** [comment]
> ![image](https://user-images.githubusercontent.com/61628421/125085878-b8ea0d80-e0d3-11eb-8a7d-d9cab65bb020.png)
> у меня вот так , у меня гугол

На двух браузерах проверил все также, инпут занимает слишком много места, чем ему требуется и прижимает лейбл.

**Comment by DmitrijMTP** [comment]
В checkbox'ах появились точки рядом
![2021-07-12_10-10](https://user-images.githubusercontent.com/85491485/125245665-83266e00-e2f9-11eb-88c2-762814169519.png)
 Отметки checked не работают также, наверно из-за этого:
![2021-07-12_10-13](https://user-images.githubusercontent.com/85491485/125246098-021ba680-e2fa-11eb-8ec2-197b2ff6debe.png)

В dropdown c количеством "кроватей" отображается с нулем
![2021-07-12_10-18](https://user-images.githubusercontent.com/85491485/125246686-c7fed480-e2fa-11eb-9248-318b22710e68.png)

**Comment by DmitrijMTP** [comment]
Чекбоксы пустые также 
![2021-07-14_15-21](https://user-images.githubusercontent.com/85491485/125621148-1abe19cd-7985-4016-a88f-93c7e7ef31dc.png)
Тут явно путь не правильный:
![2021-07-14_15-24](https://user-images.githubusercontent.com/85491485/125621543-c7d04051-19ce-4dd7-8a5c-274db71318da.png)
Плюс к этому сейчас в мастере и здесь тоже именуются часть часть изображений в img с большой буквы, это issue закрыто и там было все исправлено, но это не попало ни сюда ни в мастер

**Comment by DmitrijMTP** [comment]
Посмотрел версию, которая лежит на github pages, там работает, буду сверяться с ней тогда.

В dropdown предполагается, что это элемент формы, лучше использовать input, чтобы можно было собирать данные через form. У тебя сейчас используется  div и button. Значения присваивать лучше через input.value. Точки можно сделать через css(text-overflow)
![2021-07-14_16-27](https://user-images.githubusercontent.com/85491485/125630566-4a5e46cc-2855-4b42-adc8-52839260f94c.png)

**Comment by DmitrijMTP** [comment]
Блок отзывы: квадрат вокруг аватарки лишний и у изображения есть тень.
![2021-07-14_16-39](https://user-images.githubusercontent.com/85491485/125632018-312f2853-99c3-44c1-9ec1-a8095bff6af0.png)

Тут цвет не тот: 
![2021-07-14_16-44](https://user-images.githubusercontent.com/85491485/125632844-b96bc89b-d8fd-4387-a0f6-46b33a374bd9.png)
