### ISSUE TITLE
 Header-and-footer page

### ISSUE THREAD

**Issue by DmitrijMTP** [Ramil192/Task2#17]
Навигация: Для навигации есть симантичный тег nav, лучше его использовать, цвет шрифта не тот, в ссылке соглашения  href пустой
![2021-07-08_11-12](https://user-images.githubusercontent.com/85491485/124887718-17cd5b00-dfde-11eb-9566-fedfbf21c116.png)
Вертикальная линия не выровнена по вертикали 
![2021-07-08_11-18](https://user-images.githubusercontent.com/85491485/124887845-39c6dd80-dfde-11eb-8bc2-f32d4ee5b5cf.png)
В разметке false появляется 
![2021-07-08_11-20](https://user-images.githubusercontent.com/85491485/124888242-96c29380-dfde-11eb-9aa6-55611a5377a9.png)

В консоли ошибок не должно быть
![2021-07-08_11-22](https://user-images.githubusercontent.com/85491485/124888555-df7a4c80-dfde-11eb-87fa-e14ceda9d0e9.png)

**Comment by DmitrijMTP** [comment]
![2021-07-12_10-35](https://user-images.githubusercontent.com/85491485/125248704-0dbc9c80-e2fd-11eb-9219-135dc23be0f8.png)
По best practices href с якорем не разрешается [link](https://github.com/fullstack-development/front-end-best-practices/tree/master/HTML#2.14)

**Comment by Ramil192** [comment]
![image](https://user-images.githubusercontent.com/61628421/125349432-3d53bf00-e366-11eb-9ef5-1569d64d0e3c.png)
Я исправил но раньше , и теперь не могу прописать #17

**Comment by DmitrijMTP** [comment]
> ![image](https://user-images.githubusercontent.com/61628421/125349432-3d53bf00-e366-11eb-9ef5-1569d64d0e3c.png)
> Я исправил но раньше , и теперь не могу прописать #17

Хорошо, но это не попало в актуальною версию проекта. Сейчас если переключится на последний коммит(git checkout master) этих исправлений нет.

**Comment by DmitrijMTP** [comment]
По навигации хорошо.
В кнопках соцсетей target не появился
![2021-07-14_16-50](https://user-images.githubusercontent.com/85491485/125633667-e1c6193a-9a38-43f3-ad94-df6b530480f5.png)
