### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by DmitrijMTP** [Ramil192/Task2#18]
Немного съехала верстка
![2021-07-08_11-26](https://user-images.githubusercontent.com/85491485/124889165-70512800-dfdf-11eb-8d5c-61cbf431be18.png)
И логотипа нет в футере
![2021-07-08_11-28](https://user-images.githubusercontent.com/85491485/124889405-bd34fe80-dfdf-11eb-831f-a2a563a6c976.png)

При уменьшении ширины блок подбора номера уменьшается, а пикер остается таким же
![2021-07-08_11-31](https://user-images.githubusercontent.com/85491485/124890049-519f6100-dfe0-11eb-9894-2f9de3676c67.png)

При ширине 784px футер "разъехался" весь
![2021-07-08_11-34](https://user-images.githubusercontent.com/85491485/124890279-8ca19480-dfe0-11eb-8e37-f3c41119ed74.png)
На 550px нужно отцентрировать футер 
![2021-07-08_11-36](https://user-images.githubusercontent.com/85491485/124890662-f0c45880-dfe0-11eb-87d4-dc339a7e042b.png)

В мобильной версии фон обрезается, то есть видно только часть изображения
![2021-07-08_11-40](https://user-images.githubusercontent.com/85491485/124891340-8eb82300-dfe1-11eb-9968-0be9bb433fce.png)

**Comment by DmitrijMTP** [comment]
Переключался на 6a1cb13 и в мастер тоже, не увидел изменений, плюс пропали кнопки из инпутов
![2021-07-12_11-01_1](https://user-images.githubusercontent.com/85491485/125252356-f1226380-e300-11eb-9c1f-340fb7ae402b.png)
Возможно что-то перепуталось в коммитах

**Comment by Ramil192** [comment]
https://user-images.githubusercontent.com/61628421/125363534-76495f00-e379-11eb-8433-b5a418be0afe.mp4
