### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Azmodan95** [Ramil192/Task2#29]
Сейчас присутствуют глобальные стили для тегов, подобного быть не должно, окружение не должно влиять ни как на блоки. Блоки должны быть независимыми единицами, чтобы можно было перенести их в другой проект примеру и при этом они все так же должны выглядеть. Допускается задавать стили по тегами только для html и body, ну и border-box можно глобально задать, остальные стили должны задаваться только внутри блоков.

**Comment by Azmodan95** [comment]
Сейчас встречаются модификаторы явно привязанные к каким-то css свойствам, имена модификаторов должны быть обобщенные, так как если нужно будет изменять стили то придется менять и название модификатора, а это приведет к тому что это название придется менять по всему проекту. 
И еще если используется не булевый модификатор, то модификаторы должны именоваться в формате ключ-значение, [здесь](https://ru.bem.info/methodology/quick-start/#%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80) можешь посмотреть большее подробно о модификаторах.

**Comment by Ramil192** [comment]
повторяется но зато понятно

**Comment by Azmodan95** [comment]
1. В блоке button у модификаторов размера отсутствует значение, и префикс head лишний
2. В блоке calendar присутствует элемент `calendar__input-background-left-94`
3. Не нужно дублировать название родительского элемента у дочерних элементов, сейчас у элементов списка происходит дублирование названий к примеру  есть элемент list__item и у всех его дочерних элементов используется приставка item.
4. В блоке color-box, появился странный модификатор color-box __color_darkShade_75, ключ darkShade и значение 75, darkShade-75 это же модификатор цвета.
5. По поводу дублирования названия color-box__color_color_purple, элементов ведь является не сам цвет, а квадрат, а цвет является его модификатором. Более правильно было бы назвать color-box__square_color_purple или color-box__box_color_purple
6. Выше описанная проблема с модификаторами осталась еще в блоке price-and-number

**Comment by Ramil192** [comment]
1 В блоке button у модификаторов размера отсутствует значение (не совсем понял )
3 окей понял исправили только там , или везде исправлять (много времени займет )?

**Comment by Azmodan95** [comment]
> 1 В блоке button у модификаторов размера отсутствует значение (не совсем понял )

Имелось ввиду `button__text_head-width` есть ключ, но нет значения. https://github.com/Ramil192/Task2/blob/192c3c962150a1c15177d536a42cce8bdb7a3adf/src/components/button/button.pug#L14
Теперь появилась проблема с тем что ключ от значения отделяется тире, а не нижним подчеркиванием.

> 3 окей понял исправили только там , или везде исправлять (много времени займет )?
Да если я нахожу какую-то проблему ее нужно исправлять по всему проекту. Это сэкономит как тебе, так и мне время. И лучше серьезнее подходить к исправлению чего-то, уже возможно закончили с проверкой первого проекта, а так приходится возвращаться к одним и тем же проблемам. Если что-то не понятно, то лучше спросить.

По поводу цветов что за модификатор прозрачности появился?) Смотри к примеру можно было сделать:
```
color-box__square_color_darkest-gray
color-box__square_color_dark-gray
color-box__square_color_gray
color-box__square_color_light-gray
color-box__square_color_lightest-gray
```

---

1. В блоке bullet-list проблема с модификатором bullet-list__title_room-details, я уже писал что все не булевые модификаторы должны бы в виде ключ_значение, и тут еще есть проблема в самом названии модификатора исходя из названия этот блоке выходит что знает об его окружении.
2. Еще раз в блоке calendar инпут представлен двумя разными элементами, то есть calendar__input и calendar__input-background-position, возможно background-position имелся в качестве модификатора, но, где ключ и значение?
3. В блоке input-form проблема с модификатором input-form_width-260
