### ISSUE TITLE
Блок buttons

### ISSUE THREAD

**Issue by Azmodan95** [Ramil192/Task2#30]
https://github.com/Ramil192/Task2/blob/a03f4a1398a34f0cc755ca1e0e0a3696a4fb91b3/src/components/buttons/buttons.pug#L10
С подобным есть некоторая проблема, она заключается в том что мы можем передать абсолютно любой набор модификаторов, и для каждого из них будет создан класс, в не зависимости от того существует такой модификатор или нет. В подобных случаях мне кажется для хранения модификаторов лучше использовать объект. Ну и модификатором нужно давать более обобщенные имена. К примеру что-то вроде такого:
```
const themeModifiers = {
   filled: 'button__text_theme_filled',
   bordered: 'button__text_theme_bordered',
};
```
Ну и чтобы использовать можно применять массив:
```
const classes = [
  themeModifiers[theme]
]
```
Pug поддерживает задание классов в виде массиве, и уберет все не строковые значения из него.
Ну и здесь еще присутствует повторяющийся код, его можно избежать следующим образом:
```
const tag = type === 'link' ? 'a' : 'button';
const buttonType = type === 'link' && type;

#{tag}(class="button" href=href type=buttonType)
  span(class=['button__text'].concat(classModifier))=text
```
Еще есть нюанс, почему миксин называется buttons? Он ведь создает одну кнопку, а не несколько. И без элемента тут не обойтись? Сразу вещать стили на блок button к примеру и на модификаторы блока, просто странно элемент называется text, а ему и размеры задаются и фон)

**Comment by Azmodan95** [comment]
Почему оставил модификаторы height34 и min-width-87?

**Comment by Ramil192** [comment]
Ключ height  значение 34
