### ISSUE TITLE
ESLinst

### ISSUE THREAD

**Issue by Azmodan95** [Ramil192/Task2#36]
Нужно исправить все ошибки eslint, можно некоторые правила отключить в зависимости от ситуации, к примеру:
https://github.com/Ramil192/Task2/blob/e9237b20bceee7b8610904d545707967d8f09f9b/src/components/input-masked/MaskInput.js#L11
здесь можно было бы отключить правило для new и не создавать неиспользуемую переменную, но это если бы не нужно было бы вызывать методы экземпляра, а в данном случае вызывается метод mask, поэтому правильнее будет так:
```
const inputMask = new InputMask('99.99.9999', { placeholder: 'ДД.ММ.ГГГГ', nullable: false });
inputMask.mask(target);
```

**Comment by Ramil192** [comment]
исправил все кроме одного так как , ошибка не соответствует действительности, если помянет title то ошибка проходить.
![image](https://user-images.githubusercontent.com/61628421/133672387-fe7ff33c-6f78-4fdb-bb72-759bdfd163da.png)
ссылка на ошибку https://github.com/lndbaryshnikov/eslint-plugin-fsd/blob/master/docs/rules/no-heavy-constructor.md

**Comment by Azmodan95** [comment]
Просто отключи это правило для этой строки или для файла целиком.
```
// eslint-disable-next-line fsd/no-heavy-constructor
this.title = 'Сколько гостей';
```

**Comment by Ramil192** [comment]
https://github.com/Ramil192/Task2/commit/b340666f774ce1d58bd98d0b06bfbcc523f64b22
