### ISSUE TITLE
Отступы

### ISSUE THREAD

**Issue by DmitrijMTP** [Ramil192/Task2#4]
В некоторых местах перемешаны табы с  пробелами. Нужно пройтись и убрать везде табы
![2021-06-23_21-55](https://user-images.githubusercontent.com/85491485/123153048-edbc5a80-d46d-11eb-95a6-fe6a2bcfbd36.png)
Лучше настроить редактор, чтобы он сразу показывал какие отступы используются.

**Comment by Ramil192** [comment]
1 везде исправил 
2 настроил
