### ISSUE TITLE
Scss

### ISSUE THREAD

**Issue by DmitrijMTP** [Ramil192/Task2#6]
1. блоки стилей лучше отделять пробелами, чтобы читался код 
![2021-06-23_22-12](https://user-images.githubusercontent.com/85491485/123154972-3412b900-d470-11eb-82f9-8c81e30720cf.png)
2. @media нужно вкладывать после блока стилей к которому он применяется  
![2021-06-23_22-16](https://user-images.githubusercontent.com/85491485/123155347-ae433d80-d470-11eb-8dd3-56936f23915c.png)
3.повторяются стили 
![2021-06-23_22-20](https://user-images.githubusercontent.com/85491485/123155866-49d4ae00-d471-11eb-971d-56cf17a8cffe.png)
4.Пустой блок стилей 
![2021-06-23_22-26](https://user-images.githubusercontent.com/85491485/123156509-0cbceb80-d472-11eb-93d0-a433c9d53e0d.png)
5. Именование 
![2021-06-23_22-31](https://user-images.githubusercontent.com/85491485/123157053-c025e000-d472-11eb-86e1-d59d438c30a6.png)

**Comment by Ramil192** [comment]
1 сделал
2 сделал 
3 по моему  это был единичный случай (исправил)
4 удалил все пустые блоки 
5 исправил

**Comment by DmitrijMTP** [comment]
Селекторы по тегам, на всех элементах должны быть классы
![2021-06-29_10-59](https://user-images.githubusercontent.com/85491485/123760000-1c509000-d8c9-11eb-9eea-c4b67d3d053a.png)

**Comment by Ramil192** [comment]
Второй пункт 
header-and-footer.pug этот у мня страница ,
header-and-footer.js этот у мня точка входа,

**Comment by DmitrijMTP** [comment]
> Второй пункт
> header-and-footer.pug этот у мня страница ,
> header-and-footer.js этот у мня точка входа,

webpack  должен сам собирать стили, в js не нужно их импортировать

**Comment by Ramil192** [comment]
Это точка входа ,card.js то есть 
в card.css там только то что нужно для отрисовки страницы card.html ее не зачем знать про все стили 
если не импортировать в точку входа ,стили не подключатся и js не применяться.
1 это оптимизация 
![image](https://user-images.githubusercontent.com/61628421/123786437-58441f00-d8e2-11eb-9435-cc0aa5bf3777.png)
