### ISSUE TITLE
Js

### ISSUE THREAD

**Issue by DmitrijMTP** [Ramil192/Task2#9]
1.В таких моментах нужно кешировать элементы в переменных, чтобы каждый раз не выполнять поиск по html
![2021-06-23_22-34](https://user-images.githubusercontent.com/85491485/123157690-87d2d180-d473-11eb-9e2a-dbde773f1c26.png)
2.Приведение к числу лучше делать через специальные методы, это более безопасно, а не через "+"
![2021-06-23_23-00](https://user-images.githubusercontent.com/85491485/123160392-cae27400-d476-11eb-9c5f-e781f587b66e.png)

**Comment by Ramil192** [comment]
Насчет  пункта  под номером 2, 
1 я не нашел статей почему это плохо
2 есть typeScript чтобы следить что все правильно преобразовалось
3 jest покажет если преобразования не было
4 eslint тоже не ругался на это
у меня везде

**Comment by DmitrijMTP** [comment]
> Насчет пункта под номером 2,
> 1 я не нашел статей почему это плохо
> 2 есть typeScript чтобы следить что все правильно преобразовалось
> 3 jest покажет если преобразования не было
> 4 eslint тоже не ругался на это
Например [from airbnb](https://github.com/airbnb/javascript#type-casting--coercion). Ts, jest нет в проекте, и как ts в этом поможет не очень понятно.

**Comment by DmitrijMTP** [comment]
1.![2021-07-02_23-25](https://user-images.githubusercontent.com/85491485/124325156-dfb4bb00-db8c-11eb-99d7-82f8efdc444d.png)
Инициализацию обычно делают в отдельном файле, отдельно от класса
2.Приватные методы именуются через  "_method(){}"

**Comment by DmitrijMTP** [comment]
Все проверки содержащие более одного условия должны быть вынесены [дштл](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.9)
![2021-07-06_09-38](https://user-images.githubusercontent.com/85491485/124554027-2c72ed00-de3e-11eb-9589-64f5cb4a0083.png)
